apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: appinsightsmicroaks
  name: apigw
spec:
  selector:
    app: apigw
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer