apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigw
  template:
    metadata:
      labels:
        app: apigw
    spec:
      containers:
      - name: apigw
        image: appinsightsdp.azurecr.io/apigw:7
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "ProductionOnAKS"
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: apigwsecrets # the name of the Kubernetes secret containing the data
              key: APPINSIGHTS_INSTRUMENTATIONKEY # the key inside the Kubernetes secret containing the data      
        imagePullPolicy: Always
        ports:
        - containerPort: 80